version: '3.8'

services:
  mysqldb:
    image: mysql:latest 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "admin123"
      MYSQL_DATABASE: "DB_SST_AUTH"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin123"      
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_service_auth:/var/lib/mysql  
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  auth:
    image: diegojfcampos/sst:service-auth
    depends_on: 
      - mysqldb
    #command: bash -c "wait-for-it mysqldb:3306 -t 60 && npx prisma migrate dev"
    ports:
      - "3001:3001"        
    deploy:
      replicas: 1 
    environment:
      SECRET: "&0f1e1291%c4c1@4b99/bb76\\28dcfce45e3a|"
      DATABASE_AUTH_URL: "mysql://admin:admin123@mysqldb:3306/DB_SST_AUTH"
      FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCeIcAbA7iyJc3b\nYlxc88sMRTue2jdh5RQwTTB85qw6UFmLkMoJsVrZ16vjkHx/jnjuFzeWp1ZwnESs\n+7j0cx65shkb2EMw9G0LDbEgj3Kj/fpTY57DGyF8GcFP0e8xUaGExBcEBxhCwbeG\n15O3L+3ofw6LV6IJcNScPAynuDGIP5Hn9TrETfzR3eRdr6iAswMNGkJgsyzCtwfW\ntevf1HdrQMW91VJU52FgiQbPykCD9JbN/+Gt//YCGdGItkpH6H7ozelTJyyn65K5\nPn71cMGGCDQtgfgsku44gMZitF0gxtLPjJZOwwO1i1Gy4EzVYNPL0w/2WsYudiVy\nhZjW5VeVAgMBAAECggEAEiqCFWMROeoCOE9C7sIVE/T00J7KA6WGSGGTDe45X+jw\nzd9AI+qWK3Yi1DLk598iq7DKx98JHPO0J1kzBLt1jqipSMZzOvGsKzu98FB6ajYt\nppxzAH/3501Vegl93Iu/re8Ro8/611nGGdK0hglsCoG6K9jROnDArq1urhUzdNmG\nUiBnUIYwTMuIKfC62qwXKu/iTYvwOChFdnuoHD2EQ+2R1XeyQ0uf+XkhJFJUAx8/\n1gfEH7lMH9DemPYfRNle6cXhAv8FaIc/2C7nmBijXeGS5oYDYDBOIxLkGbWkK6jp\n/Icf/XCHUlnp+xPXfcWoj840L/ZAyXdvhyqQ565kywKBgQDawjO80qJHfNXs1p3r\nnowflIFzsTdfeLC8zUZBOfjVxJs1nKsCigC0NoGgtdemtYvEZOK+lfO52mdFia4g\nqnyiwHi9Gkd0cPtdcWYStkhWLVo/8WPDJQHSNIEIeTNYynLEjnK1LOT0qRTQ7tV7\nGhCz/mNwvLeQ+E/tUENADiGdMwKBgQC5DVnwY1AiSdU9+HuidgaGBQajlASuhOrc\nOZuw7jeDEUdjuIs75Up56z1StFw2gNuMU87F15TeSXk9B+kSF33a/x95EoMd4Xem\niMgr5wPlZ17jbba3y/cmyvs4IBwPxNQKzhVeKF9j4jTmkeT6SYpzNNoCvsKBJKoU\n4vuXMu7oFwKBgDT604zndmXZ1fWGBLkLrOP5E2DxineUwzj2fg1N/PXIp85UIxZ6\nVbFPghVp9NBrJ25pAIEnz98zBc/RiFpg7856zsL9mlCZDEeVLyNZAivcz/6sd3zL\neaVvEdD7iXP3k9QGq8E1Hj4itOfk787ggSsWcP7ctZhmivTue1sIERwBAoGAT9F+\ndb2glumZ3P0M9upJrg0E7BGwY0ZZt1vx18MolpQhYtX62H7yPNxGuyGolKnICSMt\nEREH2Ul/zd9XnMIdOxTIEoT1oTHbVi2xiZ4/g/euahKsuWJ03Hq5GWBgOjz/6Rkz\nBkYLvx2XC8zqIzsNSNwHHSAC7YlPA2tUccc6XUkCgYEAj5VoBEh9yo+ZmTYOeYcO\nwGY/ySFkA7hwctM18nzWnIZwYuSLCCWYwzgCsx32NHIgCYfbQjAnKr6MrLMJBdWI\nduCgeCPnDdxf46TD3TwWlw3z8nfTCVtzrH/4+I47QLnq/3ZeZyFTi99nBJI5JNTB\n0KiDovzShL2XfrSc0A5p9hE=\n-----END PRIVATE KEY-----\n"
      FIREBASE_API_KEY: "AIzaSyCnsZzvla26E-a62JnWOSeB9FBUXQIszmQ"
      FIREBASE_AUTH_DOMAIN: "smart-stock-tracker.firebaseapp.com"
      FIREBASE_PROJECT_ID: "smart-stock-tracker"
      FIREBASE_STORAGE_BUCKET: "smart-stock-tracker.appspot.com"
      FIREBASE_MESSAGING_SENDER_ID: "303249613100"
      FIREBASE_APP_ID: "1:303249613100:web:97b7a954aaa39a63a5cc89"
      FIREBASE_MEASUREMENT_ID: "G-7CQS7ZJQS4"
      FIREBASE_TYPE: "service_account"
      FIREBASE_CLIENT_ID: "112708692311357442799"
      FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-p4x6a@smart-stock-tracker.iam.gserviceaccount.com"
      FIREBASE_CLIENT_X509_CERT_URL: "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-p4x6a%40smart-stock-tracker.iam.gserviceaccount.com"
      FIREBASE_PRIVATE_KEY_ID: "e49badda115b26f045dc5cf9480843d5edfb65d0"
      FIREBASE_AUTH_URI: "https://accounts.google.com/o/oauth2/auth"
      FIREBASE_TOKEN_URI: "https://oauth2.googleapis.com/token"
      FIREBASE_AUTH_PROVIDER_X509_CERT_URL: "https://www.googleapis.com/oauth2/v1/certs"
      FIREBASE_UNIVERSE_DOMAIN: "googleapis.com"  

volumes:
  mysql_data_service_auth:
