pipeline {
    agent any
    
    environment {
        NODEJS_HOME = tool 'Node.js'
        PATH="${NODEJS_HOME}/bin:${PATH}"
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }

        stage('Build and Deploy') {
            steps {
                sh 'npm run build'
                
            }
        }
    }
}
