global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth'
    static_configs:
      - targets: ['https://ec2-54-196-39-73.compute-1.amazonaws.com:3001']  

  - job_name: 'earnings'
    static_configs:
      - targets: ['https://ec2-54-196-39-73.compute-1.amazonaws.com:3003']  

  - job_name: 'wallet'
    static_configs:
      - targets: ['https://ec2-54-196-39-73.compute-1.amazonaws.com:3002'] 
  
  - job_name: 'stockTax'
    static_configs:
      - targets: ['https://ec2-54-196-39-73.compute-1.amazonaws.com:3004'] 


